### ISSUE TITLE
想问下遇到安装payload时有报错,一直解决不了,不知道您解决了没有?

### ISSUE THREAD

**Issue by fencesitter1** [peng-xiao-shuai/next-demo#1]
您好,在digitalHoppo的issues里看见您关于sharp相关的报错进行了解答,所以冒昧来向您询问.现在遇到的问题就是yarn dev启动时,会有`src/get-payload.ts:4:21 - error TS2307: Cannot find module 'payload' or its corresponding type 
declarations.`的报错,但安装payload又会报错.我参考payload官网的推荐安装指令进行安装,出现的错误为:
```
PS E:\sites\digitalhippo2> npm install --save --legacy-peer-deps payload      
npm ERR! code 1
npm ERR! path E:\sites\digitalhippo2\node_modules\payload\node_modules\sharp
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
npm ERR! sharp: Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.14.5/libvips-8.14.5-win32-x64.tar.br
npm ERR! sharp: Please see https://sharp.pixelplumbing.com/install for required dependencies   
npm ERR! sharp: Installation error: connect ETIMEDOUT 20.205.243.166:443

npm ERR! A complete log of this run can be found in: C:\Users\admin\AppData\Local\npm-cache\_logs\2024-01-25T13_44_16_028Z-debug-0.log
```
尝试了您在issues的解答,但是还是没有用...

**Comment by peng-xiao-shuai** [comment]
> 您好,在digitalHoppo的issues里看见您关于sharp相关的报错进行了解答,所以冒昧来向您询问.现在遇到的问题就是yarn dev启动时,会有`src/get-payload.ts:4:21 - error TS2307: Cannot find module 'payload' or its corresponding type declarations.`的报错,但安装payload又会报错.我参考payload官网的推荐安装指令进行安装,出现的错误为:
> 
> ```
> PS E:\sites\digitalhippo2> npm install --save --legacy-peer-deps payload      
> npm ERR! code 1
> npm ERR! path E:\sites\digitalhippo2\node_modules\payload\node_modules\sharp
> npm ERR! command failed
> npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
> npm ERR! sharp: Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.14.5/libvips-8.14.5-win32-x64.tar.br
> npm ERR! sharp: Please see https://sharp.pixelplumbing.com/install for required dependencies   
> npm ERR! sharp: Installation error: connect ETIMEDOUT 20.205.243.166:443
> 
> npm ERR! A complete log of this run can be found in: C:\Users\admin\AppData\Local\npm-cache\_logs\2024-01-25T13_44_16_028Z-debug-0.log
> ```
> 
> 尝试了您在issues的解答,但是还是没有用...

node 版本 18.19.0 然后 [下载压缩包](https://github.com/lovell/sharp-libvips/releases/download/v8.14.5/libvips-8.14.5-win32-x64.tar.br)。注意压缩包所放的位置

![image](https://github.com/peng-xiao-shuai/next-demo/assets/53845479/68026946-029e-40ae-acde-a4a2cb195bb8)
